// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBp1akDb0FDoAu5dGsgfVfRqr4fY_eu2ig',
    appId: '1:407655997460:web:7675f0c90721c594280701',
    messagingSenderId: '407655997460',
    projectId: 'theresearch-14bec',
    authDomain: 'theresearch-14bec.firebaseapp.com',
    storageBucket: 'theresearch-14bec.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtIRTWAP3YgISRDMrI9uBW2Gv23NlodPk',
    appId: '1:407655997460:android:f808fa9084ac41ca280701',
    messagingSenderId: '407655997460',
    projectId: 'theresearch-14bec',
    storageBucket: 'theresearch-14bec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSw8Wcq0yJufLb4PC6KMt0sIkgEbTwZL4',
    appId: '1:407655997460:ios:ed3c9d3d1092fae5280701',
    messagingSenderId: '407655997460',
    projectId: 'theresearch-14bec',
    storageBucket: 'theresearch-14bec.appspot.com',
    androidClientId: '407655997460-1d4pcuoeevs3g3ia0umqbrc626voq0c3.apps.googleusercontent.com',
    iosClientId: '407655997460-psr86de2nbb61pfu1cui1e2spmm46a00.apps.googleusercontent.com',
    iosBundleId: 'com.rivaan.research',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSw8Wcq0yJufLb4PC6KMt0sIkgEbTwZL4',
    appId: '1:407655997460:ios:3284edb8db9fffbd280701',
    messagingSenderId: '407655997460',
    projectId: 'theresearch-14bec',
    storageBucket: 'theresearch-14bec.appspot.com',
    androidClientId: '407655997460-1d4pcuoeevs3g3ia0umqbrc626voq0c3.apps.googleusercontent.com',
    iosClientId: '407655997460-h0qip9nrhivgkuj3d2pdqaosp3r7lp0s.apps.googleusercontent.com',
    iosBundleId: 'com.rivaan.research.RunnerTests',
  );
}
